#ifndef ROS2_MSG_TYPES_H
#define ROS2_MSG_TYPES_H

enum MessageType {
  MSG_TYPE_EMPTY = 0,
  MSG_TYPE_BOOL,
  MSG_TYPE_INT8,
  MSG_TYPE_UINT8,
  MSG_TYPE_INT16,
  MSG_TYPE_INT32,
  MSG_TYPE_FLOAT32,
  MSG_TYPE_FLOAT64,
  MSG_TYPE_STRING,
  MSG_TYPE_ARRAY,
  MSG_TYPE_NONE
};

#endif /* ROS2_MSG_TYPES_H */
