#ifndef SERIAL_MESSAGE_TYPES_H
#define SERIAL_MESSAGE_TYPES_H

enum MessageType {
  MSG_TYPE_EMPTY = 0,
  MSG_TYPE_BOOL,
  MSG_TYPE_INT8,
  MSG_TYPE_UINT8,
  MSG_TYPE_INT16,
  MSG_TYPE_INT32,
  MSG_TYPE_FLOAT32,
  MSG_TYPE_FLOAT64,
  MSG_TYPE_NONE
};

#endif /* SERIAL_MESSAGE_TYPES_H */
